module.exports = {
    SAVE_CONTACT: 'SAVE_CONTACT',
    RECEIVE_CONTACTS: 'RECEIVE_CONTACTS',
    REMOVE_CONTACT: 'REMOVE_CONTACT',
    EDIT_CONTACT: 'EDIT_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT'
};
